name: simpcomp
version: "2.1.13"
license: "GPL-2.0-or-later"
date: 2021-06-07
description: |
    A GAP toolbox for simplicial complexes

authors:
    - name: Felix Effenberger
      url: https://www.linkedin.com/in/felix-effenberger-26013a146/?originalSubdomain=de
    - name: Jonathan Spreer
      url: http://www.tacet.de/Jonathan

maintainers:
    - name: Jonathan Spreer
      url: http://www.tacet.de/Jonathan

GAP: ">=4.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">=0.9999"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "io"
      version: ">=3.0"

suggested-pkgs:
    - name: "Homology"
      version: ">=1.4.4"
    - name: "GRAPE"
      version: ">=4.4"
    - name: "Gauss"
      version: ">=2011.08.22"
    - name: "MatricesForHomalg"
      version: ">=2011.10.08"
    - name: "homalg"
      version: ">=2011.10.05"
    - name: "GaussForHomalg"
      version: ">=2011.08.10"
    - name: "Modules"
      version: ">=2011.10.05"

www: https://github.com/simpcomp-team/simpcomp
readme: README.md
packageinfo: https://github.com/simpcomp-team/simpcomp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/simpcomp-team/simpcomp/releases/download/v2.1.13/simpcomp-2.1.13.tar.gz

abstract: |
    <span class="pkgname">simpcomp</span> is a <span class="pkgname">GAP</span> package for working with simplicial complexes. It allows the computation of many properties of simplicial complexes (such as the f-, g- and h-vectors, the face lattice, the automorphism group, (co-)homology with explicit basis computation, intersection form, etc.) and provides the user with functions to compute new complexes from old (simplex links and stars, connected sums, cartesian products, handle additions, bistellar flips, etc.). Furthermore, it comes with an extensive library of known triangulations of manifolds and provides the user with the possibility to create own complex libraries.<br /> <span class="pkgname">simpcomp</span> caches computed properties of a simplicial complex, thus avoiding unnecessary computations, internally handles the vertex labeling of the complexes and insures the consistency of a simplicial complex throughout all operations.<br /> <span class="pkgname">simpcomp</span> relies on the <span class="pkgname">GAP</span> package <span class="pkgname">homology</span> for its homology computation, but also provides the user with an own (co-)homology algorithm in case the packacke <span class="pkgname">homology</span> is not available. For automorphism group computation the <span class="pkgname">GAP</span> package <span class="pkgname">GRAPE</span> is used, which in turn uses the program <tt>nauty</tt> by Brendan McKay. An internal automorphism group calculation algorithm in used as fallback if the <span class="pkgname">GRAPE</span> package is not available.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    simplicial complexes, combinatorial topology, combinatorial manifolds, PL equivalence, triangulating manifolds.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>ES21</span>]   <b class='BibAuthor'>Effenberger, F. and Spreer, J.</b>,
     <i class='BibTitle'>simpcomp, A GAP toolbox for simplicial complexes,
             Version 2.1.13</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://github.com/simpcomp-team/simpcomp">https://github.com/simpcomp-team/simpcomp</a></span>.
    </p>
    

bibtex: |
    @misc{ simpcomp2.1.13,
      author =           {Effenberger, F. and Spreer, J.},
      title =            {{simpcomp}, A GAP toolbox for simplicial complexes, {V}ersion 2.1.13},
      month =            {Jun},
      year =             {2021},
      note =             {Refereed GAP package},
      howpublished =     {\href {https://github.com/simpcomp-team/simpcomp} {\texttt{https://github.com/}\discretionary {}{}{}\texttt{simpcomp-team/}\discretionary {}{}{}\texttt{simpcomp}}},
      keywords =         {simplicial complexes; combinatorial topology; combinatorial manifolds; PL equivalence; triangulating manifolds},
      printedkey =       {ES21}
    }

